---
- hosts: wordpress
  tasks:
    - name: 'Faz UPDATE e UPGRADE do SO'
      apt:
        update_cache: true
        force_apt_get: yes
        cache_valid_time: 3600
      become: yes
    - name: 'Instala pacotes de dependência do SO'
      apt: 
        name: ['php7.4', 'apache2', 'libapache2-mod-php7.4', 'php7.4-gd', 'mysql-server-8.0', 'python3-mysqldb', 'php7.4-mysql']
        state: latest
      become: yes
