Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.define "wordpress" do |m|
    m.vm.network "private_network", ip: "192.168.56.40"
    m.vm.hostname = "m104"

    m.vm.synced_folder "./ssh-keys", "/ssh-keys"

    m.vm.provision "shell", inline: "cat /ssh-keys/ansible_iac.pub >> .ssh/authorized_keys"
  end
end
