---
- hosts: all
  tasks:
  - name: 'Atualiza repositórios e pacotes do SO'
    apt:
      force_apt_get: yes
      update_cache: yes
      upgrade: 'yes'
    become: yes
    
- hosts: my_wordpress_db
  tasks:
  - name: 'Faz instalação dos pacotes necessários para o MySQL (MariaDB no caso)'
    apt:
      name: ['mariadb-server', 'mariadb-client', 'python3-pymysql']
      state: latest
    become: yes

- hosts: my_wordpress_app
  tasks:
    - name: 'Faz instalação dos pacotes necessários para o apache e php'
      apt:
        name: ['apache2', 'php', 'libapache2-mod-php', 'php-mysql']
        state: latest
      become: yes
