---
- hosts: my_wordpress_db
  handlers:
  - name: 'Reinicia MariaDB'
    service:
      name: mysql
      state: restarted
    become: yes

  tasks:
    - name: 'Atualiza senha do usuário root no mariadb'
      mysql_user:
        name: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host: 'localhost'
        password: 'superSecret03'
        priv: "*.*:ALL,GRANT"
        check_implicit_admin: true
        state: present
      become: yes
    
    - name: 'Cria o banco de dados no MariaDB'
      mysql_db:
        login_user: 'root'
        login_password: 'superSecret03'
        name: wordpress_db
        state: present
      become: yes

    - name: 'Cria usuário no mariadb para usar no wordpress'
      mysql_user:
        login_user: 'root'
        login_password: 'superSecret03'
        name: 'wordpress_user'
        password: 'superSecret03'
        priv: 'wordpress_db.*:ALL'
        state: present
        host: '192.168.56.50'

    - name: 'Altera o arquivo 50-server.cnf alterando a linha bind-address'
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        backrefs: yes
        regexp: '^bind-address'
        line: 'bind-address            = 0.0.0.0'
        state: present
      notify: 'Reinicia MariaDB'
      become: yes
