---
- hosts: my_wordpress_app
  handlers:
    - name: 'Reinicia apache2'
      service:
        name: apache2
        state: restarted
      become: yes

  tasks:
    - name: 'Copia novo arquivo de configuração do apache2'
      copy:
        src: ./files/wordpress.conf
        dest: /etc/apache2/sites-available/wordpress.conf
        owner: root
        group: root
        backup: yes
      become: yes

    - name: 'Baixa o pacote wordpress'
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /var/www/wordpress.tar.gz
        mode: '0755'
      become: yes

    - name: 'Descompacta os arquivos do wordpress'
      unarchive:
        src: /var/www/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
        mode: '0755'
      become: yes

    - name: 'Copia o arquivo de configuração do wordpress'
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes
      become: yes

    - name: 'Modifica o arquivo de configuração do wordpress'
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'password_here', value: 'superSecret03' }
        - { regex: 'localhost',  value: '192.168.56.51' }
      become: yes

    - name: 'Desabilita a configuração padrão do apache2'
      shell: 'a2dissite 000-default.conf'
      become: yes

    - name: 'Habilita nova configuração para o apache2'
      shell: 'a2ensite wordpress.conf'
      become: yes
      notify:
        - 'Reinicia apache2'
