---
- hosts: all
  tasks:
    - name: 'Atualiza senha do usuário root no mariadb'
      mysql_user:
        name: root
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host: 'localhost'
        password: 'superSecret03'
        priv: "*.*:ALL,GRANT"
        check_implicit_admin: true
        state: present
      become: yes
    
    - name: 'Cria o banco de dados no MariaDB'
      mysql_db:
        login_user: 'root'
        login_password: 'superSecret03'
        name: wordpress_db
        state: present
      become: yes

    - name: 'Cria usuário no mariadb para usar no wordpress'
      mysql_user:
        login_user: 'root'
        login_password: 'superSecret03'
        name: 'wordpress_user'
        password: 'superSecret03'
        priv: 'wordpress_db.*:ALL'
        state: present
