---
- hosts: all
  tasks:
    - name: 'Copia novo arquivo de configuração do apache2'
      copy:
        src: ./shared/wordpress.conf
        dest: /etc/apache2/sites-available/wordpress.conf
        owner: root
        group: root
        backup: yes
      become: yes

    - name: 'Desabilita a configuração padrão do apache2'
      shell: 'a2dissite 000-default.conf'
      become: yes

    - name: 'Habilita nova configuração para o apache2'
      shell: 'a2ensite wordpress.conf'
      become: yes

    - name: 'Reinicia serviço do apache2'
      shell: 'systemctl reload apache2'
      become: yes
