---
- hosts: all
  tasks:
    - name: 'Atualiza repositórios e pacotes do SO'
      apt:
        force_apt_get: yes
        update_cache: yes
        upgrade: 'yes'
      become: yes
    
    - name: 'Faz instalação dos pacotes necessários para o wordpress (LAMP)'
      apt:
        name: ['apache2', 'php', 'libapache2-mod-php', 'mariadb-server', 'mariadb-client', 'php-mysql', 'python3-pymysql']
        state: latest
      become: yes
