$copy_ssh_key_to_authorized_keys = <<-SCRIPT
  echo COPYING SSH KEY TO AUTHORIZED KEYS...
  cat /ssh-keys/ic1459.pub >> .ssh/authorized_keys
  echo COPIED!
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.define "my_wordpress" do |my|
    my.vm.network "private_network", ip: "192.168.56.50"
    my.vm.hostname = "ic1459"

    my.vm.synced_folder "./ssh-keys", "/ssh-keys"

    my.vm.provision "shell", inline: $copy_ssh_key_to_authorized_keys
  end
end
