# https://linuxconfig.org/ubuntu-20-04-wordpress-with-apache-installation

$copy_ssh_key_to_authorized_keys = <<-SCRIPT
  echo COPYING SSH KEY TO AUTHORIZED KEYS...
  cat /ssh-keys/ic1459.pub >> .ssh/authorized_keys
  echo COPIED!
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
  
  config.vm.define "my_wordpress_db" do |db|
    db.vm.network "private_network", ip: "192.168.56.51"
    db.vm.hostname = "ic1459"

    db.vm.synced_folder "./ssh-keys", "/ssh-keys"

    db.vm.provision "shell", inline: $copy_ssh_key_to_authorized_keys
  end

  config.vm.define "my_wordpress_app" do |app|
    app.vm.network "private_network", ip: "192.168.56.50"
    app.vm.hostname = "ic1459"

    app.vm.synced_folder "./ssh-keys", "/ssh-keys"

    app.vm.provision "shell", inline: $copy_ssh_key_to_authorized_keys
  end
end
